#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

#set -e

echo "start to start"
#source $OPENSHIFT_HOMEDIR"app-root/runtime/repo/.openshift/action_hooks/common"

export OPENSHIFT_RUNTIME_DIR=$OPENSHIFT_HOMEDIR"app-root/runtime"
export OPENSHIFT_RUN_DIR=${OPENSHIFT_RUNTIME_DIR}/run
export OPENSHIFT_LOG_DIR=$OPENSHIFT_HOMEDIR"diy/logs"

echo "Starting nginx."
${OPENSHIFT_RUNTIME_DIR}/nginx/sbin/nginx

echo "Starting php-fpm."
${OPENSHIFT_RUNTIME_DIR}/php5/sbin/php-fpm
